spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auto_emailsender_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  mail:
    host: smtp.gmail.com
    port: 587
    username: Vishalchitte09@gmail.com
    password: rbdzzoycvyrqmbkc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Enable scheduling

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
